version: '2'

services:
  wordpress:
    image: wordpress
    links:
      - db:mysql
    ports:
      - 8080:80
    expose:
      - 80
    volumes:
      - ./upload.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./phpinfo.php:/var/www/html/phpinfo.php

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./data:/var/lib/mysql

networks:
  outside:
    external: true